[package]
name = "kirara_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
futures-util = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
jsonwebtoken = "8.3.0"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.163"
serde_json = "1.0.96"
axum = "0.6.18"
dotenvy = "0.15.7"
sea-orm = { version = "0.12.0-rc.2", features = ["sqlx-mysql", "runtime-actix-native-tls", "macros"] }

